name: WHIMC-Habitat-Assesser
version: '${project.version}'
author: Jack Henhapl
main: edu.whimc.habitat_assesser.HabitatAssesser
api-version: '1.21'
depend: [WHIMC-QRF-Agent]
commands:
  habitats:
    permission: whimc-habitat-assessment.admin
    description: "Base command of WHIMC-Habitat-Assesser"
